---
  .travis.yml:
    hc_secure: "CHtnS2PAX/8KykXWVIqJ24mK8lBnNLUaj/JKojX5kzgwxnYlIvzWQf3q5gMU5iowsEZX/z+zP23W9ARG0AkQNvevJrDt7MvZcxg4sHOrsuqP2Vbme77UM46We5uhwX+fQSQYCdVmATw6NGrq1eJGR295UltbCSzC3e/7WuMrTxg="
  spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
    unmanaged: true
  spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
    unmanaged: true
